In [3]:
X=5
X=input()
print(X)
type(X)

222
222


str

In [10]:
pairs = {1:"apple", "orange": [2, 3, 4],  True: False, None: "True", False:22}  
print(pairs)

{1: False, 'orange': [2, 3, 4], None: 'True', False: 22}


In [14]:
pairs = {1: "apple", "orange": [2, 3, 4],  True: False, None: "True"}  
print(pairs)

{1: False, 'orange': [2, 3, 4], None: 'True'}


In [15]:
print(pairs.items())

dict_items([(1, False), ('orange', [2, 3, 4]), (None, 'True')])


In [16]:
for x in range(2, 20, 3):
    print(x)

2
5
8
11
14
17


In [18]:
counter = 0
while counter<0:
    print("Inside loop")
    counter = counter + 1
else:
    print("Inside else")

Inside else


In [19]:
import numpy as np
new_array = np.array([[1,2,3],[4,5,6]])
print(new_array[0,0], new_array[0,1])

1 2


In [30]:
print(np.random.random((3,3)))
print(np.random.randint(0,10, size=(3,4)))

[[0.85613546 0.0170939  0.10257392]
 [0.61181016 0.21232651 0.47987577]
 [0.05586679 0.15442945 0.61153066]]
[[3 8 6 1]
 [8 2 5 6]
 [6 2 6 5]]


In [37]:
print(np.zeros(3))
print(np.full((3,3),5))
print(np.eye(3))
print(np.ones((2,3))*8)

[0. 0. 0.]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[8. 8. 8.]
 [8. 8. 8.]]


In [38]:
t1=np.array([1,2])
t2=np.array([3,4])
print(np.add(t1, t2))
print(t1+t2)

[4 6]
[4 6]


In [49]:
print(np.subtract([3,4], [1,2]))
print([[1,2],[3,4],[5,6]][True])

[2 2]
[3, 4]


In [59]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
print(a[a%2!=0])

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [61]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
print(a[a%2!=0])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  3  5  7  9 11]


In [63]:
import pandas as pd
fruits = ['apple', 'orange', 'kiwi', 'avocado']
quantities=[10,2,5,12]
rest=[12,3,56,4]
a1=pd.Series(quantities, index=fruits)
a2=pd.Series(rest, index=fruits)
print(a1)
print(a1+a2)

apple      10
orange      2
kiwi        5
avocado    12
dtype: int64
apple      22
orange      5
kiwi       61
avocado    16
dtype: int64


In [74]:
import numpy as np
import pandas as pd
my_numpy_array=np.random.randn(3,4)
df=pd.DataFrame(my_numpy_array, columns=list("abcd"))
print(df)
df.to_csv('rand.csv')
new=pd.read_csv('rand.csv')
new.head(100)

          a         b         c         d
0 -2.206939  1.111274  1.328856  0.438723
1 -0.102557 -1.485804 -0.131811  0.149092
2  0.276954 -0.808888 -0.896834  0.300632


Unnamed: 0         a         b         c         d
0           0 -2.206939  1.111274  1.328856  0.438723
1           1 -0.102557 -1.485804 -0.131811  0.149092
2           2  0.276954 -0.808888 -0.896834  0.300632

In [73]:
new.tail(1)

Unnamed: 0         a        b         c         d
2           2 -0.992334 -0.77424 -0.550483  0.305982

In [76]:
new=new.drop('Unnamed: 0', axis=1)
new

a         b         c         d
0 -2.206939  1.111274  1.328856  0.438723
1 -0.102557 -1.485804 -0.131811  0.149092
2  0.276954 -0.808888 -0.896834  0.300632

In [77]:
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      float64
 1   b       3 non-null      float64
 2   c       3 non-null      float64
 3   d       3 non-null      float64
dtypes: float64(4)
memory usage: 224.0 bytes


In [79]:
new['a'].describe()

count    3.000000
mean    -0.677514
std      1.338044
min     -2.206939
25%     -1.154748
50%     -0.102557
75%      0.087199
max      0.276954
Name: a, dtype: float64

In [82]:
new_selection = new[['a', 'b']]
new_selection

a         b
0 -2.206939  1.111274
1 -0.102557 -1.485804
2  0.276954 -0.808888

In [92]:
new_rows = new[0:1]
new_rows

a         b         c         d
0 -2.206939  1.111274  1.328856  0.438723

In [89]:
new_selection=new.iloc[:, :]
new_selection

a         b         c         d
0 -2.206939  1.111274  1.328856  0.438723
1 -0.102557 -1.485804 -0.131811  0.149092
2  0.276954 -0.808888 -0.896834  0.300632

In [106]:
new_selection=new.loc[0:1,'b':'d']
new_selection

b         c         d
0  1.111274  1.328856  0.438723
1 -1.485804 -0.131811  0.149092

In [107]:
new_selection=new.loc[1,'b':'d']
new_selection

b   -1.485804
c   -0.131811
d    0.149092
Name: 1, dtype: float64

In [108]:
new_index = new.set_index('b')
new_index

a         c         d
b                                      
 1.111274 -2.206939  1.328856  0.438723
-1.485804 -0.102557 -0.131811  0.149092
-0.808888  0.276954 -0.896834  0.300632

In [110]:
new_data=new[new['b']>0]
new_data

a         b         c         d
0 -2.206939  1.111274  1.328856  0.438723

In [111]:
new['ab']=new['a']+new['b']
new

a         b         c         d        ab
0 -2.206939  1.111274  1.328856  0.438723 -1.095665
1 -0.102557 -1.485804 -0.131811  0.149092 -1.588361
2  0.276954 -0.808888 -0.896834  0.300632 -0.531934

In [113]:
new=new.drop(['ab'], axis=1)
new

a         b         c         d
0 -2.206939  1.111274  1.328856  0.438723
1 -0.102557 -1.485804 -0.131811  0.149092
2  0.276954 -0.808888 -0.896834  0.300632

In [114]:
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      float64
 1   b       3 non-null      float64
 2   c       3 non-null      float64
 3   d       3 non-null      float64
dtypes: float64(4)
memory usage: 224.0 bytes
